rootProject.name = "jvm-www"

include(":runtime-core")
include(":runtime-testkit")
include(":runtime-android")
include(":runtime-android-testkit")
include(":web-events")
include(":web-events-testkit")
include(":web-encoding")
include(":web-encoding-testkit")
include(":web-console")
include(":web-console-testkit")
include(":web-console-android")
include(":web-console-android-testkit")
include(":web-url")
include(":web-url-testkit")
include(":web-bodies")
include(":web-bodies-testkit")
include(":web-fetch-core")
include(":web-fetch-testkit")
include(":web-fetch-okhttp")
include(":web-fetch-okhttp-testkit")
